// <auto-generated />
using System;
using Bibliotheque_LIPAJOLI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bibliotheque_LIPAJOLI.Migrations
{
    [DbContext(typeof(BibliothequeContext))]
    partial class BibliothequeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Bibliotheque_LIPAJOLI.Models.Emprunt", b =>
                {
                    b.Property<string>("CodeLivre")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumAbonne")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEmprunt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRetour")
                        .HasColumnType("TEXT");

                    b.HasKey("CodeLivre", "NumAbonne");

                    b.HasIndex("NumAbonne");

                    b.ToTable("Emprunt");
                });

            modelBuilder.Entity("Bibliotheque_LIPAJOLI.Models.Livre", b =>
                {
                    b.Property<string>("CodeLivre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Auteurs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn10")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn13")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Prix")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CodeLivre");

                    b.ToTable("Livre");
                });

            modelBuilder.Entity("Bibliotheque_LIPAJOLI.Models.Usager", b =>
                {
                    b.Property<string>("NumAbonne")
                        .HasColumnType("TEXT");

                    b.Property<int>("Defaillance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("NumAbonne");

                    b.ToTable("Usager");
                });

            modelBuilder.Entity("Bibliotheque_LIPAJOLI.Models.Emprunt", b =>
                {
                    b.HasOne("Bibliotheque_LIPAJOLI.Models.Livre", "Livre")
                        .WithMany()
                        .HasForeignKey("CodeLivre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bibliotheque_LIPAJOLI.Models.Usager", "Usager")
                        .WithMany("Emprunts")
                        .HasForeignKey("NumAbonne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Usager");
                });

            modelBuilder.Entity("Bibliotheque_LIPAJOLI.Models.Usager", b =>
                {
                    b.Navigation("Emprunts");
                });
#pragma warning restore 612, 618
        }
    }
}
